# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b23c7080b57abdfda2aaa79be948023035f5142677a205597d0333060c767c10595eebc6404e2532fc040f478b1e9863905217da51c3240f93b04171ca35b572

test:
  secret_key_base: d141027c69c0066eba5b607f4b43d8c863f82bf4d4f1294bc91ec95511acf4d6883c9c852d773d00927eea671e742c4c4851f2266fdb9f80e24ecd97f0e5784e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
